### PR TITLE
added social icons for slideshare.net

### PR DESCRIPTION
**Pull request by MatthiasLohr**
Added a new nice social icon: Slideshare.net!

### CODE REVIEW

**Comment by cristianraiber** [comment]
@MatthiasLohr - this will get merged in v2.4.0

**Comment by MatthiasLohr** [comment]
Yeah, thanks! When will that be?

**Comment by cristianraiber** [comment]
@MatthiasLohr - no more than 1 week from today :) I've started fixing all the theme's issue. Once I'm done, I'll release an update.

**Comment by cristianraiber** [comment]
@MatthiasLohr - Implemented here: https://github.com/puikinsh/Sparkling/pull/215/commits/c076b6a383021b565ee657c020c9a5fa7d399b3b

**Pull request closed without merging**
