### PR TITLE
Added support for Google fonts subset

### PR DESCRIPTION
**Pull request by ms32035**
Useful for extended character sets.

### CODE REVIEW

**Comment by FreeWPTP** [comment]
I tested this commit on my test site using latest version of Sparkling theme but it generated the following error message in the front end of site.

`Parse error: syntax error, unexpected '[' in /colorlib-git/wp-content/themes/Sparkling/functions.php on line 213`

**Comment by ms32035** [comment]
Hard to tell what it is.

Tested it also for non-existing option key
`
$font_subset = of_get_option('main_body_typography')['subset_key_missing'];
wp_register_style( 'sparkling-fonts', '//fonts.googleapis.com/css?family=Open+Sans:400italic,400,600,700|Roboto+Slab:400,300,700'.( empty($font_subset) ? '' : '&subset='.$font_subset ));
`
and had no issues.
What does `of_get_option('main_body_typography')` return?

**Comment by FreeWPTP** [comment]
Tested it again and got the same error message as shown in the below screenshot.

screenshot 11

I am testing it using PHP Version 5.3.8

What's your PHP version?

Have you tested it setting WP debug to true?

You can see yourself what's the function of_get_option is returning in its below code.

```
function of_get_option( $name, $default = false ) {

	$option_name = '';
	// Get option settings from database
	$options = get_option( 'sparkling' );

	// Return specific option
	if ( isset( $options[$name] ) ) {
		return $options[$name];
	}

	return $default;
}
```

**Comment by ms32035** [comment]
I'm using 5.6 and the issue is due to [direct array dereferencing](http://stackoverflow.com/questions/17545812/php-5-3-accessing-array-key-from-object-getter) which was introduced in 5.4. Will prepare a version that is backwards compatible tomorrow.

**Comment by ms32035** [comment]
@FreeWPTP how's testing of the fix?

**Comment by cristianraiber** [comment]
@giucu91 - please look at this.

**Comment by ms32035** [comment]
@cristianraiber @puikinsh, can this finally be merged?

**Comment by cristianraiber** [comment]
This has been implemented here: https://github.com/puikinsh/Sparkling/pull/189

Will be available in the theme's next release.

**Pull request closed without merging**
