### PR TITLE
2.4.0 Update

### PR DESCRIPTION
**Pull request by cristianraiber**

### CODE REVIEW

**Comment by MatthiasLohr** [comment]
When do you think will 2.4.0 be released?

**Comment by cristianraiber** [comment]
@MatthiasLohr - Very soon.

**Comment by cristianraiber** [comment]
@MatthiasLohr - That's one of the links with issues, since we also have acm.org, the regex pattern used can't distinguish between just acm.org and dl.acm.org. 

We're basically going to be using just the acm.org icon.

**Comment by MatthiasLohr** [comment]
The following code would solve the problem with acm/acmdl:
```css
a[href*="acm.org"]:not([href*="dl.acm.org"]) {
  ...
}
a[href*="dl.acm.org"] {
  ...
}
```

**Comment by cristianraiber** [comment]
@MatthiasLohr - totally right :) Will push an update to address this as well. Tiredness got the best of me, apparently :)

**Comment by cristianraiber** [comment]
@MatthiasLohr - expect this update to be released sometime this week (probably mid-week).

Thanks,
Cristian.

**Comment by MatthiasLohr** [comment]
I'm looking forward to it.

**Comment by MatthiasLohr** [comment]
Yeah :) Great! Thank you so much! When will it be available via the Wordpress Update feature?

**Comment by cristianraiber** [comment]
As soon as @puikinsh uploads it :)

**Comment by MatthiasLohr** [comment]
Then i hope that will not take too long

**Comment by cristianraiber** [comment]
@MatthiasLohr - version 2.4.0 is out as of 5 mintues ago :)

**Comment by MatthiasLohr** [comment]
My wordpress still doesn't find the update ;)

**Comment by MatthiasLohr** [comment]
Yeah! Now!

**Comment by cristianraiber** [comment]
Feel free to open a ticket here if you find any issues with it. As always, software can sometimes be buggy, no matter how much we test it before releasing :)

**Comment by MatthiasLohr** [comment]
I know. But my first impression: Works fine (https://mlohr.com/)

Thank you very much!

**Comment by cristianraiber** [comment]
And the ORCID icon you wanted is also there and working fine :) 

🎉

**Pull request merged**
